#!/bin/bash

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Download package
wget http://http.us.debian.org/debian/pool/main/a/adminer/adminer_4.2.1-1_all.deb

# Install package
sudo dpkg -i adminer_4.2.1-1_all.deb
rm adminer_4.2.1-1_all.deb

sudo ln -s /usr/share/adminer/adminer /var/www/html/adminer
sudo ln -s /usr/share/adminer/designs/konya/adminer.css /usr/share/adminer/adminer/adminer.css
sudo ln -s /usr/share/adminer/externals /var/www/html/externals
