#!/bin/bash

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

# Install node from new package
curl -sL https://deb.nodesource.com/setup | sudo bash -


# Install package
apt-get install nodejs --assume-yes
apt-get install nodejs --assume-yes